properties([
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '15')),
])

node('auto-u18-x64-01') {

    stage('Clear workspace') {
        cleanWs()
    }

    stage('Load data') {
        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/$BRANCH_NAME']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [
                    $class: 'SubmoduleOption',
                    disableSubmodules: false,
                    parentCredentials: true,
                    recursiveSubmodules: true,
                    reference: '',
                    trackingSubmodules: false,
                ]
            ],
            gitTool: 'Default',
            submoduleCfg: [],
            userRemoteConfigs: [
                [
                    credentialsId: '11b939ca-039c-4d09-868f-376b0f6007e3',
                    url: 'http://gitlab.aladdin.ru/QAJenkins/USBRedirectorAPI.git',
                ]
            ],
        ])

    }

    stage('Setup') {
        sh(script: """#!/bin/bash
            python3 -m venv "pyvenv"
            source "pyvenv/bin/activate"
            python3 -m pip install -U pip
            python3 -m pip install -r ./requirements-jenkins.txt
        """)
    }

    stage('Run') {

        sh(script: """#!/bin/bash
            source "pyvenv/bin/activate"
            python3 -m flake8 --exit-zero --format=html --htmldir=flake-report --exclude=pyvenv
        """)

    }
    stage('Publish HTML') {
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'flake-report', reportFiles: 'index.html', reportName: 'Flake8 report', reportTitles: ''])
    }
}